<?php

namespace AppBundle\Entity;

/**
 * ApiLeagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiLeagueRepository extends \Doctrine\ORM\EntityRepository
{
}
