<?php

namespace AppBundle\Entity;

/**
 * ApiTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
